type Group = {
  id: number;
  automatic: boolean;
  name: string;
  display_name: string;
  user_count: number;
  mentionable_level: number;
  messageable_level: number;
  visibility_level: number;
  primary_group: boolean;
  title?: string;
  grant_trust_level?: string;
  incoming_email?: string;
  has_messages: boolean;
  flair_url?: string | null;
  flair_bg_color?: string | null;
  flair_color?: string | null;
  bio_raw?: string | null;
  bio_cooked?: string | null;
  bio_excerpt?: string | null;
  public_admission: boolean;
  public_exit: boolean;
  allow_membership_requests: boolean;
  full_name?: string | null;
  default_notification_level: number;
  membership_request_template?: string | null;
  is_group_user?: boolean;
  is_group_owner?: boolean;
  members_visibility_level: number;
  can_see_members: boolean;
  can_admin_group: boolean;
  can_edit_group?: boolean;
  publish_read_state: boolean;
};
