export const JOBS = {
  EXTRACT: 'EXTRACT',
  TRANSFORM: 'TRANSFORM',
  LOAD: 'LOAD',

  BADGES: 'BADGES',
  GROUPS: 'GROUPS',
  GROUP_MEMBERS: 'GROUP_MEMBERS',
  POSTS: 'POSTS',
  TAGS: 'TAGS',
  TOPICS: 'TOPICS',
  USER_ACTIONS: 'USER_ACTIONS',
  USER_BADGES: 'USER_BADGES',
  CATEGORIES: 'CATEGORIES',
};
