export const BADGE_QUEUE = 'BADGE_QUEUE';
export const BADGE_TYPE_QUEUE = 'BADGE_TYPE_QUEUE';
export const BADGE_GROUPING_QUEUE = 'BADGE_GROUPING_QUEUE';

export const QUEUES = {
  FORUM: 'FORUM',
  USER: 'USER',
  BADGE: 'BADGE',
  BADGE_TYPE: 'BADGE_TYPE',
  BADGE_GROUPING: 'BADGE_GROUPING',
  POST: 'POST',
  TOPIC: 'TOPIC',
  TAG: 'TAG',
  TAG_GROUP: 'TAG_GROUP',
  CATEGORY: 'CATEGORY',
  GROUP: 'GROUP',
};
